import { describe, it, expect, beforeEach } from 'vitest';

import type { LlmProvider, StreamResult } from './provider.js';
import { getProvider, registerProvider, resetProvider } from './provider.js';

function makeFakeProvider(name: string): LlmProvider {
  return {
    name,
    generate: async () => `generated by ${name}`,
    stream: async (_prompt, onText): Promise<StreamResult> => {
      onText('chunk');
      return { fullText: 'chunk', usage: { inputTokens: 1, outputTokens: 1 } };
    },
    checkHealth: async () => ({ status: 'ok', latencyMs: 1 }),
  };
}

describe('LLM provider registry', () => {
  beforeEach(() => {
    resetProvider();
  });

  it('throws when getProvider is called before registration', () => {
    expect(() => getProvider()).toThrow(/not registered/);
  });

  it('returns the registered provider', async () => {
    const fake = makeFakeProvider('fake');
    registerProvider(fake);

    const provider = getProvider();

    expect(provider.name).toBe('fake');
    expect(await provider.generate({ system: '', user: 'prompt' })).toBe('generated by fake');
  });

  it('later registrations replace earlier ones', () => {
    registerProvider(makeFakeProvider('first'));
    registerProvider(makeFakeProvider('second'));

    expect(getProvider().name).toBe('second');
  });

  it('reset clears the active provider', () => {
    registerProvider(makeFakeProvider('fake'));
    resetProvider();

    expect(() => getProvider()).toThrow(/not registered/);
  });

  it('registered providers satisfy the LlmProvider contract', async () => {
    const fake = makeFakeProvider('contract-check');
    registerProvider(fake);

    const provider = getProvider();
    const deltas: string[] = [];

    const result = await provider.stream({ system: '', user: 'any' }, (d) => deltas.push(d));

    expect(deltas).toEqual(['chunk']);
    expect(result.fullText).toBe('chunk');
    expect(result.usage.inputTokens).toBe(1);

    const health = await provider.checkHealth();
    expect(health.status).toBe('ok');
  });
});
